apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: apricode-exchange
data:
  # Application
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_NAME: "Apricode Exchange"
  NEXT_PUBLIC_APP_URL: "https://app.bitflow.biz"
  
  # Database
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "apricode"
  
  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Feature Flags
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"

